### ISSUE TITLE
[GTA III] Can't look up or down with mouse for "Standard" PC controls

### ISSUE THREAD

**Issue by ViperAcidZX** [CookiePLMonster/SilentPatch#129]
I'm using the 2024 Hotfix version of SilentPatch with Ultimate ASI Loader 7.7.0 and for whatever reason the game's mouselook features when set to Standard controls does not let me look up or down at all with this version of SilentPatch installed. This wasn't an issue in the pre-2024 versions I've tried but for some reason I can't use the modern mouse controls when I wanted to. Can you please investigate this? This happened on a v1.0 EXE for the game.

UPDATE: Oddly enough, this does not affect controller's vertical look when using GInput III despite how old it is compared to SilentPatch III but it's the mouse's vertical axis with the Standard controls that are broken with the current version of SilentPatch.

**Comment by CookiePLMonster** [comment]
What other mods do you have? Is this also happening without SP? Also check the mouse sensitivity in options.

**Comment by ViperAcidZX** [comment]
I tried it without any other mods at all other than Ultimate ASI Loader so SilentPatch can work, and when I erased my configuration file for the game, SilentPatch literally set the game's mouse sensitivity set to 0 with a fresh configuration file. It was only when I clicked "Restore Defaults" for the control settings and messed with the Mouse Sensitivity settings a bit that the mouse began working again.

UPDATE: So I put back my mods, deleted my game's configuration file, ran into the same issues as before until I repeated what I did earlier to undo SilentPatch making the mouse sensitivity default to 0 in the Control settings from the Options menu.

**Comment by CookiePLMonster** [comment]
I had this reported once in the past but I was unable to reproduce this so far. I'll need to try again.

**Comment by CookiePLMonster** [comment]
Reproduced. It happens when SP loads "too early", but the real issue is that I have not fully ported this fix from III 1.1:
> Mouse sensitivity is now properly saved – like in the 1.1 and Steam versions.

Vice City got the same fix later in SP (but not in the official patches), and there I've done it properly, but in III it's partially broken. I'll upgrade both III and VC fixes to resolve this issue for the next hotfix.

**Comment by ViperAcidZX** [comment]
Thank you Silent! I hope someday GInput for these games can get a glow up like this too.

**Comment by CookiePLMonster** [comment]
I finally got to fixing that:

* GTA III got a full rewrite of this fix, fully porting the changes from III 1.1. It now works fine regardless of whether UAL is installed or not.
* GTA VC was already correct, but I corrected the hooks to be consistent with my new III approach.

It'll be part of the next hotfix/release.

**Comment by ViperAcidZX** [comment]
I don't know if it's a Windows 11 issue or something with updating to a newer version of Ultimate ASI Loader, but the issue seems to be happening again until I manually reset the controls then change the mouse sensitivity.

**Comment by anthoncast** [comment]
I can confirm. This issue persists. Basically the game settings are written with the mouse sensitivity to 0...

**Comment by CookiePLMonster** [comment]
It's fixed in the upcoming release.
